{
	"openapi": "3.1.0",
	"info": {
		"title": "URL Shortener API",
		"version": "1.0.0",
		"description": "API para encurtar URLs com autenticação multi-tenant"
	},
	"servers": [
		{
			"url": "http://localhost:3000"
		}
	],
	"paths": {
		"/tenants": {
			"post": {
				"summary": "Cria um novo tenant",
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"required": ["name"],
								"properties": {
									"name": {
										"type": "string"
									}
								}
							}
						}
					}
				},
				"responses": {
					"201": {
						"description": "Tenant criado com sucesso",
						"content": {
							"application/json": {
								"example": {
									"apiKey": "dummy-api-key",
									"createdAt": "2025-05-07T03:48:46.544Z",
									"deletedAt": null,
									"id": "0196a837-6bc0-7379-96ba-f42cd2d8f259",
									"name": "tenant do pedro",
									"updatedAt": null
								}
							}
						}
					},
					"400": {
						"description": "Erro de validação",
						"content": {
							"application/json": {
								"example": {
									"errors": ["Name is required"],
									"message": "Invalid body schema"
								}
							}
						}
					}
				}
			}
		},
		"/users": {
			"post": {
				"summary": "Cria um novo usuário",
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"required": ["name", "email", "password", "confirmPassword"],
								"properties": {
									"name": { "type": "string" },
									"email": { "type": "string" },
									"password": { "type": "string" },
									"confirmPassword": { "type": "string" }
								}
							}
						}
					}
				},
				"responses": {
					"201": {
						"description": "Usuário criado com sucesso",
						"content": {
							"application/json": {
								"example": {
									"createdAt": "2025-05-07T03:51:47.729Z",
									"deletedAt": null,
									"email": "pedro@gmail.com",
									"id": "0196a83a-2f8b-74ac-96d8-a5d97df6ff1e",
									"name": "pedro",
									"password": "$2b$10$...",
									"tenantId": "0196a837-6bc0-7379-96ba-f42cd2d8f259",
									"updatedAt": null
								}
							}
						}
					},
					"404": {
						"description": "Tenant não encontrado",
						"content": {
							"application/json": {
								"example": {
									"message": "Tenant not found",
									"status": "error"
								}
							}
						}
					},
					"400": {
						"description": "Erro de validação",
						"content": {
							"application/json": {
								"example": {
									"errors": ["Confirm password is required"],
									"message": "Invalid body schema"
								}
							}
						}
					}
				}
			}
		},
		"/users/sign-in": {
			"post": {
				"summary": "Autenticação de usuário",
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"required": ["email", "password"],
								"properties": {
									"email": { "type": "string" },
									"password": { "type": "string" }
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Login bem-sucedido",
						"content": {
							"application/json": {
								"example": {
									"accessToken": "dummy-token",
									"expiresIn": "1h",
									"prefix": "Bearer"
								}
							}
						}
					},
					"401": {
						"description": "Credenciais inválidas",
						"content": {
							"application/json": {
								"example": {
									"message": "Invalid password or email"
								}
							}
						}
					}
				}
			}
		},
		"/urls/shorten": {
			"post": {
				"summary": "Cria uma URL encurtada",
				"security": [{ "bearerAuth": [] }],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"required": ["originalUrl"],
								"properties": {
									"originalUrl": { "type": "string" }
								}
							}
						}
					}
				},
				"responses": {
					"201": {
						"description": "URL encurtada com sucesso",
						"content": {
							"application/json": {
								"example": {
									"url": "http://localhost:3000/m7UxvR"
								}
							}
						}
					},
					"400": {
						"description": "Erro de validação",
						"content": {
							"application/json": {
								"example": {
									"errors": ["OriginalUrl must be at most 255 characters long", "Invalid URL"],
									"message": "Invalid body schema"
								}
							}
						}
					}
				}
			}
		},
		"/urls": {
			"get": {
				"summary": "Lista todas as URLs do usuário ou tenant",
				"security": [{ "bearerAuth": [] }],
				"responses": {
					"200": {
						"description": "Lista de URLs",
						"content": {
							"application/json": {
								"example": [
									{
										"clickCount": 2,
										"code": "m7UxvR",
										"createdAt": "2025-05-08T00:37:41.513Z",
										"deletedAt": null,
										"id": "0196acae-d67d-701a-bbd0-542062639ec9",
										"originalUrl": "https://www.youtube.com/...",
										"tenantId": "3eff6d1b-eaff-4fc3-b754-d79282327351",
										"updatedAt": "2025-05-08T01:46:28.670Z",
										"userId": null
									}
								]
							}
						}
					},
					"401": {
						"description": "Token JWT inválido",
						"content": {
							"application/json": {
								"example": {
									"message": "Invalid JWT token"
								}
							}
						}
					}
				}
			}
		},
		"/urls/{id}": {
			"patch": {
				"summary": "Atualiza a URL original de um encurtamento",
				"security": [{ "bearerAuth": [] }],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				],
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"type": "object",
								"required": ["originalUrl"],
								"properties": {
									"originalUrl": { "type": "string" }
								}
							}
						}
					}
				},
				"responses": {
					"204": { "description": "Atualizado com sucesso" },
					"400": {
						"description": "Erro de validação",
						"content": {
							"application/json": {
								"example": {
									"errors": ["OriginalUrl is required"],
									"message": "Invalid body schema"
								}
							}
						}
					},
					"404": {
						"description": "Não encontrado",
						"content": {
							"application/json": {
								"example": {
									"message": "Could not update original url"
								}
							}
						}
					}
				}
			},
			"delete": {
				"summary": "Deleta uma URL encurtada",
				"security": [{ "bearerAuth": [] }],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				],
				"responses": {
					"204": { "description": "Excluído com sucesso" },
					"401": {
						"description": "Token inválido",
						"content": {
							"application/json": {
								"example": {
									"message": "Invalid JWT token"
								}
							}
						}
					}
				}
			}
		},
		"/{shortUrlCode}": {
			"get": {
				"summary": "Redireciona para a URL original",
				"parameters": [
					{
						"name": "shortUrlCode",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				],
				"responses": {
					"302": { "description": "Redirecionamento para a URL original" },
					"404": {
						"description": "URL não encontrada",
						"content": {
							"application/json": {
								"example": {
									"message": "Url not found"
								}
							}
						}
					}
				}
			}
		}
	},
	"components": {
		"securitySchemes": {
			"bearerAuth": {
				"type": "http",
				"scheme": "bearer",
				"bearerFormat": "JWT"
			}
		}
	}
}
